Auth branch
anastasiya-charnahayeva/mini-paint pull request #1
Opened 2024-06-18 11:05 UTC by anastasiya-charnahayeva

auth block

2024-06-28 14:14 UTC, AliaksandrInnowise requested changes

2024-06-28 14:14 UTC, ghost commented on package.json
>      "lint-staged": "^15.2.5",
All of the dependencies which are listed in "Dependencies" are included in a bundle. So please pay attention to exclude dev runtime only to "DevDependencies"
`lint-staged` is only used during commit time, so it should be in dev ones

2024-06-28 14:14 UTC, ghost commented on src/App.vue
>    <div>
An empty divs again 👀

2024-06-28 14:14 UTC, ghost commented on src/App.vue
> +  onMounted(() => {
This one is nice to be a part of auth store and not directly inside of a component

2024-06-28 14:14 UTC, ghost commented on src/firebase.config.js
In this the same file with /index.js inside of this directory. By the way extension is .js and not a .ts

2024-06-28 14:14 UTC, ghost commented on src/stores/modules/useAuth.ts
> +    const user = ref();
I think there should be some typescript errors here

2024-06-28 14:14 UTC, ghost commented on src/views/Login.vue
> +  const alert_variant = ref<string>("bg-blue-500");
Inconsistent naming again 👀  Don't change for now, but please pay attention

2024-06-30 17:58 UTC, anastasiya-charnahayeva commented on src/stores/modules/useAuth.ts
> +    const user = ref();
?

2024-07-02 06:13 UTC, merged